# This file was generated by GoReleaser. DO NOT EDIT.
class Alug < Formula
  desc "CLI command to generate the URL to login AWS console."
  homepage "https://github.com/shirakiya/alug"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/shirakiya/alug/releases/download/0.0.1/alug_0.0.1_darwin_amd64.tar.gz"
    sha256 "9797444332c53e732291b88fc8d80f6a9d9f967911a90c1daf1e91c5bd335bd0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/shirakiya/alug/releases/download/0.0.1/alug_0.0.1_linux_amd64.tar.gz"
      sha256 "3f230ffe129426dee7803172b02f6a3d8922074c7039eba9b43da1716e436eed"
    end
  end

  def install
    bin.install "alug"
  end

  test do
    system "#{bin}/alug -v"
  end
end
