# This file was generated by GoReleaser. DO NOT EDIT.
class Alug < Formula
  desc "CLI command to generate the URL to login AWS console."
  homepage "https://github.com/shirakiya/alug"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/shirakiya/alug/releases/0.0.1/alug_0.0.1_darwin_amd64.tar.gz"
    sha256 "114fe3abc000f9f1702f676b793643c07c7a2873ca3055c4e73bf03ee353c124"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/shirakiya/alug/releases/0.0.1/alug_0.0.1_linux_amd64.tar.gz"
      sha256 "a5a9678972fa4fb70764b72dbceeca49875d38374414d6d0cd640b7e4ead321b"
    end
  end

  def install
    bin.install "alug"
  end

  test do
    system "#{bin}/alug -v"
  end
end
